# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from led_controller import led_controller
import sys


class Ui_MainWindow(object):
    def __init__(self):
        self.controller = led_controller()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 442)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.red = QtWidgets.QRadioButton(self.centralwidget,
                                          clicked=lambda: self.controller.red()
                                          )
        self.red.setGeometry(QtCore.QRect(200, 110, 113, 28))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(16)
        font.setItalic(True)
        self.red.setFont(font)
        self.red.setObjectName("red")
        self.red.setStyleSheet("QRadioButton"
                               "{"
                               "background-color : red"
                               "}"
                               )

        self.green = QtWidgets.QRadioButton(self.centralwidget,
                                            clicked=lambda:
                                                self.controller.green()
                                            )
        self.green.setGeometry(QtCore.QRect(200, 170, 113, 28))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(16)
        font.setItalic(True)
        self.green.setFont(font)
        self.green.setObjectName("green")
        self.green.setStyleSheet("QRadioButton"
                                 "{"
                                 "background-color : lightgreen"
                                 "}"
                                 )
        self.blue = QtWidgets.QRadioButton(self.centralwidget,
                                           clicked=lambda:
                                               self.controller.blue()
                                           )
        self.blue.setGeometry(QtCore.QRect(200, 230, 113, 28))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(16)
        font.setItalic(True)
        self.blue.setFont(font)
        self.blue.setObjectName("blue")
        self.blue.setStyleSheet("QRadioButton"
                                "{"
                                "background-color : lightblue"
                                "}"
                                )
        self.exit = QtWidgets.QPushButton(self.centralwidget,
                                          clicked=lambda: self.clean_exit()
                                          )
        self.exit.setGeometry(QtCore.QRect(180, 310, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.exit.setObjectName("exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 538, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.red.setText(_translate("MainWindow", "Red"))
        self.green.setText(_translate("MainWindow", "Green"))
        self.blue.setText(_translate("MainWindow", "Blue"))
        self.exit.setText(_translate("MainWindow", "Exit"))

    def clean_exit(self):
        self.controller.reset()
        sys.exit()
